apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pacma-mongo-db
  name: mongo
  namespace: pacman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pacman-mongo-db
  template:
    metadata:
      labels:
        app: pacman-mongo-db
    spec:
      containers:
      - image: centos/mongodb-36-centos7
        name: mongo
        env:
        - name: MONGODB_ADMIN_PASSWORD
          value: clyde
        - name: MONGODB_DATABASE
          value: pacman
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: mongodb-users-secret
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: mongodb-users-secret
        readinessProbe:
          exec:
           command:
            - /bin/sh
            - -i
            - -c
            - mongo 127.0.0.1:27017/$MONGODB_DATABASE -u $MONGODB_USER -p $MONGODB_PASSWORD
              --eval="quit()"
        ports:
        - name: mongo
          containerPort: 27017
        volumeMounts:
          - name: mongo-db
            mountPath: /data/db
      volumes:
        - name: mongo-db
          persistentVolumeClaim:
            claimName: pvc-mongo-db

